HMIS-1209 Spike for terraform
hmcts/hmi-apim-infrastructures pull request #1
Opened 2023-07-12 13:59 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/HMIS-1209

### Change description ###

Add multiple policy files for endpoints.

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2023-07-13 08:14 UTC, joshblackmoor reviewed
Policy files will need updating but assuming that will happen in the later tickets

2023-07-13 08:14 UTC, joshblackmoor commented on .idea/.gitignore
.idea/ folder should be included in the gitignore

2023-07-13 08:17 UTC, joshblackmoor reviewed
You also need to do the infra approvals before merge. See message in pipeline regarding it

2023-07-17 14:22 UTC, junaidiqbalmoj commented on .idea/.gitignore
added in gitignore.

2023-07-17 14:23 UTC, junaidiqbalmoj reviewed
sds infra changes have been approved and pipeline is green now.

2023-07-17 14:41 UTC, joshblackmoor reviewed
Code looks fine, can still see .idea folder though

2023-07-17 14:53 UTC, ChrisS1512 requested changes

2023-07-17 14:53 UTC, ChrisS1512 commented on resources/api-spec/hmi-api-health.json
> +  "host": "hmi-apim.dev.platform.hmcts.net",
Should this host be configurable / it replaces the dev with the relevant env it's running in?

2023-07-17 14:54 UTC, ChrisS1512 requested changes

2023-07-17 14:54 UTC, ChrisS1512 commented on resources/api-spec/hmi-api-health.json
> +            "description": "",
Can a description be added for this

2023-07-17 14:54 UTC, ChrisS1512 requested changes

2023-07-17 14:54 UTC, ChrisS1512 commented on resources/policy-files/CaTH/publication.xml
> +        <set-backend-service base-url="https://hmi-apim.test.publication.platform.hmcts.net/hmi/" />
Similar here (and the api-policy.xml file)

2023-07-18 08:00 UTC, joshblackmoor approved these changes

2023-07-18 08:32 UTC, merged